parameters:
    almaviacx.calameo.api.key: ~
    almaviacx.calameo.api.secret: ~
    almaviacx.calameo.http_client.config: []

services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  AlmaviaCX\Calameo\API\HttpClient:
    arguments:
      $APIKey: "%almaviacx.calameo.api.key%"
      $APISecret: "%almaviacx.calameo.api.secret%"
      $config: "%almaviacx.calameo.http_client.config%"

  AlmaviaCX\Calameo\API\Serializer:
    arguments:
      $baseSerializer: "@jms_serializer"

  AlmaviaCX\Calameo\API\Gateway\:
    resource: "../../../../lib/API/Gateway/*"

  AlmaviaCX\Calameo\API\Repository\:
    resource: "../../../../lib/API/Repository/*"

  AlmaviaCX\Calameo\API\Service\:
    resource: "../../../../lib/API/Service/*"
